"""Add in_newsletter field to user

Revision ID: 6cc8ad1090a8
Revises: 30e0cebce435
Create Date: 2025-04-15 09:21:49.223448

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cc8ad1090a8"
down_revision: Union[str, None] = "30e0cebce435"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "in_newsletter",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "in_newsletter")
    # ### end Alembic commands ###
